---
  #   Section 1.1
  - name: "Section 1.1 | Level 1"
    block:
      - name: "[1.1.1] | "
        include: section1/level1/1.1/1.1.1.yml

#      - name: "[1.1.2-1.1.10] | "
#        include: section1/level1/1.1/1.1.2.10.yml

#      - name: "[1.1.11-1.1.24] | "
#        include: section1/level1/1.1/1.1.11.24.yml
    when:
      - level1 is defined and level1
    check_mode: "{{ global_check_mode }}"
    tags:
      - section1.1
