---
  # Section 1.7 Command Line Warning Banners
  - name: "[block name][1.7] CLWB"
    block:

      - name: "[1.7.1.1][Automated] |
          Ensure message of the day is configured properly"
        template:
          src: etc/motd.j2
          dest: /etc/motd
        tags:
          - automated
          - section1.7.1.1

      - name: "[1.7.1.2][Automated] |
          Ensure local login warning banner is configured properly"
        template:
          src: etc/issue.j2
          dest: /etc/issue
        tags:
          - automated
          - section1.7.1.2

      - name: "[1.7.1.3][Automated] |
          Ensure remote login warning banner is configured properly"
        template:
          src: etc/issue.net.j2
          dest: /etc/issue.net
        tags:
          - automated
          - section1.7.1.3

      - name: "[1.7.1.4 - 1.7.1.6][Automated] |
          Ensure permissions on /etc/ ./motd, ./issue and ./issue.net are configured"
        file:
          path: /etc/{{ item }}
          owner: root
          group: root
          mode: 0644
        with_items:
          - motd
          - issue
          - issue.net
        tags:
          - automated
          - section1.7.1.4
          - section1.7.1.5
          - section1.7.1.6
    when:
      - level1 is defined and level1
    check_mode: "{{ global_check_mode }}"
    tags:
      - section1.7
